### PR TITLE
Add basic ui component structure using the MVP pattern

### PR DESCRIPTION
**Pull request by Marcarrian**

### CODE REVIEW

**Comment by bbortt** [comment]
You did not merge `master` correctly. There should only be *1* merge commit. We don't want all the commits duplicated in `master`!

**Comment by bbortt** [comment]
> You did not merge master correctly. There should only be 1 merge commit. We don't want all the commits duplicated in master!

Sorry, my bad.. it's
> into feature/#21-grundstruktur-ui-komponenten from master

Please do this locally using `git checkout feature/#21-grundstruktur-ui-komponenten && git merge origin/master`.

**Comment by Marcarrian** [comment]
Gibt es dafür keine einstellung im Github?

**Comment by Marcarrian** [comment]
Frage mich eher, warum mein Commit hier gar nicht drin ist

**Pull request closed without merging**
